name: lip-std
channels:
  - pytorch
  - defaults
dependencies:
  - ignite=0.3.0=py37_0
  - matplotlib=3.1.3
  - numpy=1.18.1
  - pillow=7.0.0
  - pip=20.0.2=py37_1
  - python=3.7.6
  - pytorch=1.2.0
  - scipy=1.4.1
  - seaborn=0.10.0
  - setuptools=45.1.0
  - pip:
    - pandas==1.0.1
    - scikit-learn==0.22.1
    - tensorboard==2.1.0
    - torchvision==0.4.2
